on:
    push

jobs:
    demo1: 
        runs-on: ubuntu-latest
        steps:
          - name: step1
            run: echo "Ol√°, mundo"
          - name: step2
            run: 
                echo "Mensagem2"
                echo "Mensagem3"
                ls -la