name: Demo de Workflow
on:
    push

jobs:
    demo1: 
        runs-on: ubuntu-latest
        steps:
          - name: step1
            run: echo "Ol√°, mundo"
          - name: step2
            run: 
                echo "Mensagem2"
                echo "Mensagem3"
                ls -la
    demo2:
        runs-on: ubuntu-latest
        needs: demo1
        steps:
         - name: Etapa 1
           run: echo "Estou na etapa 1"
